
package com.viks.demo.generatedSrcFromWSDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewXds", targetNamespace = "http://www.yarcloud.ru/er76/", wsdlLocation = "https://test-med.yarcloud.ru/newxds-external/ws/service?wsdl")
public class NewXds_Service
    extends Service
{

    private final static URL NEWXDS_WSDL_LOCATION;
    private final static WebServiceException NEWXDS_EXCEPTION;
    private final static QName NEWXDS_QNAME = new QName("http://www.yarcloud.ru/er76/", "NewXds");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://test-med.yarcloud.ru/newxds-external/ws/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWXDS_WSDL_LOCATION = url;
        NEWXDS_EXCEPTION = e;
    }

    public NewXds_Service() {
        super(__getWsdlLocation(), NEWXDS_QNAME);
    }

    public NewXds_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWXDS_QNAME, features);
    }

    public NewXds_Service(URL wsdlLocation) {
        super(wsdlLocation, NEWXDS_QNAME);
    }

    public NewXds_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWXDS_QNAME, features);
    }

    public NewXds_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewXds_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewXds
     */
    @WebEndpoint(name = "DocumentExternalWebService")
    public NewXds getDocumentExternalWebService() {
        return super.getPort(new QName("http://www.yarcloud.ru/er76/", "DocumentExternalWebService"), NewXds.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewXds
     */
    @WebEndpoint(name = "DocumentExternalWebService")
    public NewXds getDocumentExternalWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.yarcloud.ru/er76/", "DocumentExternalWebService"), NewXds.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWXDS_EXCEPTION!= null) {
            throw NEWXDS_EXCEPTION;
        }
        return NEWXDS_WSDL_LOCATION;
    }

}
