
package om.viks.demo.generatedSrcFromWSDL;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewXds", targetNamespace = "http://www.yarcloud.ru/er76/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewXds {


    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetCovid19InfomationResponse
     */
    @WebMethod(operationName = "GetCovid19Infomation", action = "GetCovid19Infomation")
    @WebResult(name = "GetCovid19InfomationResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetCovid19InfomationResponse")
    public GetCovid19InfomationResponse getCovid19Infomation(
        @WebParam(name = "GetCovid19InfomationRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetCovid19InfomationRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetPersonalDocumentsResponse
     */
    @WebMethod(operationName = "GetPersonalDocuments", action = "GetPersonalDocuments")
    @WebResult(name = "GetPersonalDocumentsResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetPersonalDocumentsResponse")
    public GetPersonalDocumentsResponse getPersonalDocuments(
        @WebParam(name = "GetPersonalDocumentsRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetPersonalDocumentsRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetActualTypeSemdResponse
     */
    @WebMethod(operationName = "GetActualTypeSemd", action = "GetActualTypeSemd")
    @WebResult(name = "GetActualTypeSemdResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetActualTypeSemdResponse")
    public GetActualTypeSemdResponse getActualTypeSemd(
        @WebParam(name = "GetActualTypeSemdRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetActualTypeSemdRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetDocumentResponse
     */
    @WebMethod(operationName = "GetDocument", action = "GetDocument")
    @WebResult(name = "GetDocumentResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetDocumentResponse")
    public GetDocumentResponse getDocument(
        @WebParam(name = "GetDocumentRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetDocumentRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetIdentificatorsByMoResponse
     */
    @WebMethod(operationName = "GetIdentificatorsByMo", action = "GetIdentificatorsByMo")
    @WebResult(name = "GetIdentificatorsByMoResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetIdentificatorsByMoResponse")
    public GetIdentificatorsByMoResponse getIdentificatorsByMo(
        @WebParam(name = "GetIdentificatorsByMoRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetIdentificatorsByMoRequest parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns om.viks.demo.generatedSrcFromWSDL.GetPersonalBySnilsResponse
     */
    @WebMethod(operationName = "GetPersonalBySnils", action = "GetPersonalBySnils")
    @WebResult(name = "GetPersonalBySnilsResponse", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "GetPersonalBySnilsResponse")
    public GetPersonalBySnilsResponse getPersonalBySnils(
        @WebParam(name = "GetPersonalBySnilsRequest", targetNamespace = "http://www.yarcloud.ru/er76/", partName = "parameter")
        GetPersonalBySnilsRequest parameter);

}
